directories:
  dataset_dir: "../head_datasets/ADNI_train_dataset/"
  validation_dataset_dir: "../head_datasets/ADNI_validation_dataset/"
  test_dataset_dir: "../head_datasets/ADNI_test_dataset/"
  results_dir: "./results_ddpm_ADNI"
  sample_dir: "./gen_datasets"
  checkpoints_dir: "./results/"

parameters:

sampling:
  num_samples: 3
  label: "CN"
  seed: 48
  checkpoint: "107"
  ema: True
  mask_id: #"005_S_0610"

dataset:
  info_masks: "../head_datasets/ADNI_test_dataset/diagnosis/test_subjects.csv"
  masks: "../head_datasets/ADNI_test_dataset/mask"
  data_len: 60 # for all
  seed: 36
  num_samples: 1
  run: "260320_095902"
